kind: Deployment
apiVersion: apps/v1
metadata:
  name: gritadmin
  namespace: water
  labels:
    app: gritadmin
  annotations:
    deployment.kubernetes.io/revision: '5'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gritadmin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gritadmin
      annotations:
        kubesphere.io/restartedAt: '2021-12-01T05:43:31.992Z'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: container-5hrrmj
          image: 'registry.cn-hangzhou.aliyuncs.com/noearorg/gritadmin:latest'
          ports:
            - name: http-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: gritadmin.user
              value: admin
            - name: gritadmin.password
              value: 3ksqYpnd2a9vIOsQ
            - name: TZ
              value: Asia/Shanghai
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
