kind: Deployment
apiVersion: apps/v1
metadata:
  name: wateradmin
  namespace: water
  labels:
    app: wateradmin
  annotations:
    deployment.kubernetes.io/revision: '112'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["10.0.0.193"],"port":32507,"protocol":"TCP","serviceName":"water:wateradmin","allNodes":true}]
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wateradmin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wateradmin
      annotations:
        kubesphere.io/restartedAt: '2021-12-01T05:42:54.155Z'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: container-g77qk7
          image: 'registry.cn-hangzhou.aliyuncs.com/noearorg/wateradmin:latest'
          ports:
            - name: http-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
