kind: Deployment
apiVersion: apps/v1
metadata:
  name: watersev-pln
  namespace: water
  labels:
    app: watersev-pln
  annotations:
    deployment.kubernetes.io/revision: '29'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watersev-pln
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: watersev-pln
      annotations:
        kubesphere.io/restartedAt: '2021-12-01T05:43:04.784Z'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: container-r1jaup
          image: 'registry.cn-hangzhou.aliyuncs.com/noearorg/watersev:latest'
          ports:
            - name: http-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: water.sss
              value: pln
            - name: TZ
              value: Asia/Shanghai
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
