solon.extend: "waterpaas_ext"

server.port: 9374
server.request.maxRequestSize: "2mb"

#water:
#  host: "waterapi"
#  logger: "water_log_paas"
#  service:
#    name: "waterpaas"
#    secretKey: "0zJt0J88TkIvqYgC"


solon.app:
  name: "waterpaas"
  group: "water"


solon.cloud.water:
  server: "waterapi"
  log:
    default: "water_log_paas"
  event:
    seal: "0zJt0J88TkIvqYgC"

