solon.extend: "waterpaas_ext"

server.port: 9374
server.request.maxRequestSize: "2mb"

water:
  host: "waterapi.water"
  logger: "water_log_paas"
  service:
    name: "waterpaas"
    secretKey: "0zJt0J88TkIvqYgC"


solon.app:
  name: "waterpaas"
  group: "water"
