version: "3"

services:
  waterapi:
    image: noearorg/waterapi
    container_name: waterapi
    environment:
      water.ds.schema: water #默认可以不要
      water.ds.server: ${server}
      water.ds.username: ${username}
      water.ds.password: ${password}
    ports:
      - 9371:8080
  watersev:
    image: noearorg/watersev:latest
    container_name: watersev
    ports:
      - 9372:8080
    links:
      - waterapi
    depends_on:
      - waterapi
  wateradmin:
    image: noearorg/wateradmin:latest
    container_name: wateradmin
    ports:
      - 9373:8080
    links:
      - waterapi
    depends_on:
      - waterapi
  waterpaas:
    image: noearorg/waterpaas:latest
    container_name: waterpaas
    ports:
      - 9374:8080
    links:
      - waterapi
    depends_on:
      - waterapi
  waterraas:
    image: noearorg/waterraas:latest
    container_name: waterraas
    ports:
      - 9376:8080
    links:
      - waterapi
    depends_on:
      - waterapi
networks:
  default:
    external:
      name: water-net