
water:
  host: "http://water2"
  service:
    name: "water-demo-dubbo"
    secretKey: "NJ8f6usfroGRi7iR"

dubbo:
  application:
    name: hello-consume
    owner: noear
  registry:
#    address: nacos://192.168.8.118:8848
    address: water://water2