server.port: 8011

water:
  host: "http://water2"
  service:
    name: "water-demo-dubbo-provider"
    secretKey: "NJ8f6usfroGRi7iR"

dubbo:
  application:
    name: hello-provider
    owner: noear
  registry:
    address: water://water2