solon.extend: "waterraas_ext"

server.port: 9376

water:
  host: "waterapi"
  logger: "water_log_raas"
  service:
    name: "waterraas"
    host: "@water/raas_uri"
    secretKey: "qTYzsNjzCN9I44FB"

solon.app:
  name: "waterraas"
  group: "water"