server.port: 9371
server.request.maxRequestSize: 2mb

solon.extend: water_ini


solon.app:
  name: waterapi
  group: water

solon.logging.appender:
  console:
    level: "INFO"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"