solon.extend: "waterfaas_ext"

server.port: 9374
server.request.maxRequestSize: "2mb"

solon.app:
  name: "waterfaas"
  group: "water"

solon.cloud.water:
  server: "waterapi:9371"
  log:
    default: "water_log_faas"
  event:
    seal: "0zJt0J88TkIvqYgC"

solon.logging.appender:
  console:
    level: "INFO"

solon.logging.logger:
  "org.eclipse.jetty":
    level: "WARN"
  "com.zaxxer.hikari":
    level: "WARN"


waterfaas.secretKey: "0zJt0J88TkIvqYgC"
