solon.extend: "watersev_ext"

server.port: 9372

solon.app:
  name: "watersev"
  group: "water"

solon.cloud.water:
  server: "waterapi"
  log:
    default: "water_log_sev"
  event:
    seal: "0kqvJpJ3dsSGCPoH"
