solon.extend: "watersev_ext"

server.port: 9372

solon.app:
  name: "watersev"
  group: "water"

solon.cloud.water:
  server: "waterapi:9371"
  log:
    default: "water_log_sev"
  event:
    seal: "0kqvJpJ3dsSGCPoH"

solon.logging.appender:
  console:
    level: "INFO"

solon.logging.logger:
  "org.eclipse.jetty":
    level: "WARN"
  "com.zaxxer.hikari":
    level: "WARN"
