version: '3'

# 注意事项：
# 1.运行之前，先运行 Water 助理 完成初始化
# 2.把 water.ds.* 换成 WaterDb
# 4.管理后台地址 http://localhost:9373

services:
  waterapi:
    image: noearorg/waterapi:latest
    container_name: waterapi
    environment:
      - water.ds.schema=water
      - water.ds.server=mysql.water.io:3306
      - water.ds.username=demo
      - water.ds.password=1234
      - TZ=Asia/Shanghai
    ports:
      - 9371:8080
  watersev:
    image: noearorg/watersev:latest
    container_name: watersev
    environment:
      - solon.cloud.water.server=waterapi:8080
      - TZ=Asia/Shanghai
    depends_on:
      -  waterapi
    ports:
      - 9372:8080
  wateradmin:
    image: noearorg/wateradmin:latest
    container_name: wateradmin
    environment:
      - solon.cloud.water.server=waterapi:8080
      - TZ=Asia/Shanghai
    depends_on:
      -  waterapi
    ports:
      - 9373:8080
  waterpaas:
    image: noearorg/waterpaas:latest
    container_name: waterpaas
    environment:
      - solon.cloud.water.server=waterapi:8080
      - TZ=Asia/Shanghai
    depends_on:
      -  waterapi
    ports:
      - 9374:8080
  waterraas:
    image: noearorg/waterraas:latest
    container_name: waterraas
    environment:
      - solon.cloud.water.server=waterapi:8080
      - TZ=Asia/Shanghai
    depends_on:
      -  waterapi
    ports:
      - 9375:8080
