solon.extend: wateradmin_ext

server.port: 9373
server.session.timeout: 360000 #10h

solon.app:
  name: "wateradmin"
  group: "water"
  title: "WATER"

waterpaas.secretKey: "0zJt0J88TkIvqYgC"

solon.cloud.water:
  server: "waterapi"
  log:
    default: "water_log_admin"
  event:
    seal: "b5fZK49x71Rnn5Cl"

#water:
#  host: "waterapi"
#  logger: "water_log_admin"
#  service:
#    tag: "water"
#    name: "wateradmin"
#    secretKey: "b5fZK49x71Rnn5Cl"

#water.weed.log.style: "text2"

#water.log:
#  gzip: 1
#  level: 2
#  interval: 1000
#  packetSize: 100
