solon.extend: wateradmin_ext

server.port: 9373
server.session.timeout: 7200

bcf.root: "water_admin"

water:
  host: "http://water2"
  service:
    name: "wateradmin"
    secretKey: "b5fZK49x71Rnn5Cl"


#water.log:
#  gzip: 1
#  level: 2
#  interval: 1000
#  packetSize: 100