solon.extend: wateradmin_ext

server.port: 9373
server.session.timeout: 7200

solon.app:
  name: "wateradmin"
  title: "WATER"
  group: "water"

waterpaas.secretKey: "0zJt0J88TkIvqYgC"

water:
  host: "water"
  logger: "water_log_admin"
  service:
    tag: "water"
    name: "wateradmin"
    secretKey: "b5fZK49x71Rnn5Cl"

#water.weed.log.style: "text2"

#water.log:
#  gzip: 1
#  level: 2
#  interval: 1000
#  packetSize: 100


water.dataSource.schema: water
water.dataSource.url: jdbc:mysql://mysql.water.io:3306/water?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
water.dataSource.username: water
water.dataSource.password: KHe85E4MYdeLBHSR
water.dataSource.driverClassName: com.mysql.jdbc.Driver